# Generated by Django 2.2.6 on 2020-11-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Дайте короткое название задаче', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Опишите суть задачи', verbose_name='Текст')),
                ('slug', models.SlugField(blank=True, help_text='Укажите адрес для страницы задачи. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=100, unique=True, verbose_name='Адрес для страницы с задачей')),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='tasks/', verbose_name='Картинка')),
            ],
        ),
    ]
