# Generated by Django 2.2.6 on 2020-10-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20201029_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, help_text='Хелп для title', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(help_text='Хелп для text', verbose_name='Текст'),
        ),
    ]
