# Generated by Django 2.2.6 on 2020-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20201031_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, help_text='Хелп для slug', max_length=1, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Хелп для title', max_length=2, verbose_name='Заголовок'),
        ),
    ]
