# Generated by Django 2.2.6 on 2020-11-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_auto_20201104_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='tasks/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите адрес для страницы задачи. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=100, unique=True, verbose_name='Адрес для страницы с задачей'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(help_text='Опишите суть задачи', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Дайте короткое название задаче', max_length=100, verbose_name='Заголовок'),
        ),
    ]
