# Generated by Django 2.2.6 on 2020-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Хелп для text', max_length=100, verbose_name='Текст')),
                ('slug', models.SlugField(blank=True, help_text='A valid email address, please.', max_length=100, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, help_text='A valid email address, please.', null=True, upload_to='tasks/', verbose_name='Картинка')),
            ],
        ),
    ]
